package com.xtrmetl.etl.job;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.xtrmetl.etl.service.EtlBatchProperties;
import com.xtrmetl.etl.service.EtlRequestLock;
import com.xtrmetl.etl.service.EtlService;
import com.xtrmetl.etl.service.Sha256Digest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Proves that ledger, target writes, and exact-live-lease success commit or roll back together.
 */
@SpringJUnitConfig(EtlJobExecutionServiceIntegrationTest.TestConfiguration.class)
class EtlJobExecutionServiceIntegrationTest {

    private static final String OWNER_ID = "worker-alpha";
    private static final String PAYLOAD = """
            [{"id":"record_alpha","name":"accepted","email":"USER@EXAMPLE.COM"}]
            """;

    private final EtlJobExecutionService executionService;
    private final EtlJobLeaseRepository leaseRepository;
    private final EtlJobIdempotencyService idempotencyService;
    private final JdbcTemplate jdbcTemplate;

    @Autowired
    EtlJobExecutionServiceIntegrationTest(
            EtlJobExecutionService executionService,
            EtlJobLeaseRepository leaseRepository,
            EtlJobIdempotencyService idempotencyService,
            JdbcTemplate jdbcTemplate
    ) {
        this.executionService = executionService;
        this.leaseRepository = leaseRepository;
        this.idempotencyService = idempotencyService;
        this.jdbcTemplate = jdbcTemplate;
    }

    @BeforeEach
    void createTables() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS processed_data");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_idempotency_records");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_job_records");
        jdbcTemplate.execute("""
                CREATE TABLE etl_job_records (
                    job_record_id UUID PRIMARY KEY,
                    principal_scope_hash CHAR(64) NOT NULL,
                    submission_key_hash CHAR(64) NOT NULL,
                    request_digest CHAR(64) NOT NULL,
                    request_payload CLOB,
                    job_status VARCHAR(32) NOT NULL,
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    failure_code VARCHAR(128),
                    lease_claim_id UUID,
                    lease_owner_id VARCHAR(128),
                    lease_expires_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE processed_data (
                    processed_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data VARCHAR(8192) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_idempotency_records (
                    idempotency_key_hash CHAR(64) PRIMARY KEY,
                    request_digest CHAR(64) NOT NULL,
                    response_body CLOB NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void commitsLedgerTargetRowsAndTerminalSuccessInOneTransaction() {
        UUID jobRecordId = insertPendingJob();
        EtlJobLease lease = leaseRepository.claimNext(
                OWNER_ID,
                Duration.ofMinutes(5),
                3
        ).orElseThrow();

        executionService.execute(lease);

        assertEquals(jobRecordId, lease.jobRecordId());
        assertEquals(1, tableCount("processed_data"));
        assertEquals(1, tableCount("etl_idempotency_records"));
        assertEquals(
                "ID:record_alpha,NAME:ACCEPTED,EMAIL:user@example.com,",
                jdbcTemplate.queryForObject("SELECT data FROM processed_data", String.class)
        );
        assertEquals("SUCCEEDED", jobStatus(jobRecordId));
        assertEquals(0, retainedPayloadCount(jobRecordId));
    }

    @Test
    void rollsBackLedgerAndTargetRowsWhenTheClaimWasSuperseded() {
        UUID jobRecordId = insertPendingJob();
        EtlJobLease lease = leaseRepository.claimNext(
                OWNER_ID,
                Duration.ofMinutes(5),
                3
        ).orElseThrow();
        jdbcTemplate.update(
                "UPDATE etl_job_records SET lease_claim_id = ? WHERE job_record_id = ?",
                UUID.randomUUID(),
                jobRecordId
        );

        assertThrows(StaleEtlJobLeaseException.class, () -> executionService.execute(lease));

        assertUncommittedDurableEffects(jobRecordId);
    }

    @Test
    void rollsBackLedgerAndTargetRowsWhenTheLeaseExpiredBeforeExecution() {
        UUID jobRecordId = insertPendingJob();
        EtlJobLease lease = leaseRepository.claimNext(
                OWNER_ID,
                Duration.ofMinutes(5),
                3
        ).orElseThrow();
        jdbcTemplate.update(
                "UPDATE etl_job_records SET lease_expires_at = ? WHERE job_record_id = ?",
                Instant.now().minusSeconds(1),
                jobRecordId
        );

        assertThrows(StaleEtlJobLeaseException.class, () -> executionService.execute(lease));

        assertUncommittedDurableEffects(jobRecordId);
    }

    @Test
    void rejectsMissingCollaboratorsOrLease() {
        assertThrows(
                NullPointerException.class,
                () -> new EtlJobExecutionService(null, leaseRepository)
        );
        assertThrows(
                NullPointerException.class,
                () -> new EtlJobExecutionService(idempotencyService, null)
        );
        assertThrows(NullPointerException.class, () -> executionService.execute(null));
    }

    private void assertUncommittedDurableEffects(UUID jobRecordId) {
        assertEquals(0, tableCount("processed_data"));
        assertEquals(0, tableCount("etl_idempotency_records"));
        assertEquals("RUNNING", jobStatus(jobRecordId));
        assertEquals(1, retainedPayloadCount(jobRecordId));
    }

    private UUID insertPendingJob() {
        UUID jobRecordId = UUID.randomUUID();
        Instant now = Instant.now();
        jdbcTemplate.update(
                """
                INSERT INTO etl_job_records (
                    job_record_id, principal_scope_hash, submission_key_hash,
                    request_digest, request_payload, job_status, attempt_count,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, 'PENDING', 0, ?, ?)
                """,
                jobRecordId,
                "a".repeat(64),
                "b".repeat(64),
                Sha256Digest.digest(PAYLOAD),
                PAYLOAD,
                now,
                now
        );
        return jobRecordId;
    }

    private int tableCount(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + tableName,
                Integer.class
        );
        return count == null ? 0 : count;
    }

    private String jobStatus(UUID jobRecordId) {
        return jdbcTemplate.queryForObject(
                "SELECT job_status FROM etl_job_records WHERE job_record_id = ?",
                String.class,
                jobRecordId
        );
    }

    private int retainedPayloadCount(UUID jobRecordId) {
        Integer count = jdbcTemplate.queryForObject(
                """
                SELECT COUNT(*)
                FROM etl_job_records
                WHERE job_record_id = ?
                  AND request_payload IS NOT NULL
                """,
                Integer.class,
                jobRecordId
        );
        return count == null ? 0 : count;
    }

    /**
     * Transaction-enabled execution context using one database for job, ledger, and target effects.
     */
    @Configuration
    @EnableTransactionManagement
    static class TestConfiguration {

        @Bean
        DataSource dataSource() {
            return new EmbeddedDatabaseBuilder()
                    .generateUniqueName(true)
                    .setType(EmbeddedDatabaseType.H2)
                    .build();
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        EtlBatchProperties etlBatchProperties() {
            return new EtlBatchProperties();
        }

        @Bean
        ObjectMapper objectMapper() {
            return new ObjectMapper();
        }

        @Bean
        EtlRequestLock etlRequestLock() {
            return idempotencyKeyHash -> true;
        }

        @Bean
        EtlService etlService(
                JdbcTemplate jdbcTemplate,
                ObjectMapper objectMapper,
                EtlBatchProperties properties,
                EtlRequestLock requestLock
        ) {
            return new EtlService(jdbcTemplate, objectMapper, properties, requestLock);
        }

        @Bean
        EtlJobIdempotencyService etlJobIdempotencyService(
                JdbcTemplate jdbcTemplate,
                EtlService etlService,
                EtlRequestLock requestLock
        ) {
            return new EtlJobIdempotencyService(jdbcTemplate, etlService, requestLock);
        }

        @Bean
        EtlJobLeaseRepository etlJobLeaseRepository(
                JdbcTemplate jdbcTemplate,
                PlatformTransactionManager transactionManager
        ) {
            return new EtlJobLeaseRepository(jdbcTemplate, transactionManager);
        }

        @Bean
        EtlJobExecutionService etlJobExecutionService(
                EtlJobIdempotencyService idempotencyService,
                EtlJobLeaseRepository leaseRepository
        ) {
            return new EtlJobExecutionService(idempotencyService, leaseRepository);
        }
    }
}
