package com.xtrmetl.etl.job;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.xtrmetl.etl.service.EtlBatchProperties;
import com.xtrmetl.etl.service.EtlRequestLock;
import com.xtrmetl.etl.service.EtlService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.dao.CannotAcquireLockException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Proves that durable jobs reuse the response ledger without retaining raw identity values.
 */
@SpringJUnitConfig(EtlJobIdempotencyServiceIntegrationTest.TestConfiguration.class)
class EtlJobIdempotencyServiceIntegrationTest {

    private static final String OWNER_ID = "worker-alpha";
    private static final String PRINCIPAL_SCOPE_HASH = "a".repeat(64);
    private static final String SUBMISSION_KEY_HASH = "b".repeat(64);
    private static final String PAYLOAD = """
            [{"id":"record_alpha","name":"accepted","email":"USER@EXAMPLE.COM"}]
            """;

    private final EtlJobIdempotencyService idempotencyService;
    private final EtlService etlService;
    private final EtlRequestLock requestLock;
    private final JdbcTemplate jdbcTemplate;

    @Autowired
    EtlJobIdempotencyServiceIntegrationTest(
            EtlJobIdempotencyService idempotencyService,
            EtlService etlService,
            EtlRequestLock requestLock,
            JdbcTemplate jdbcTemplate
    ) {
        this.idempotencyService = idempotencyService;
        this.etlService = etlService;
        this.requestLock = requestLock;
        this.jdbcTemplate = jdbcTemplate;
    }

    @BeforeEach
    void createTables() {
        reset(requestLock);
        when(requestLock.tryLock(anyString())).thenReturn(true);
        jdbcTemplate.execute("DROP TABLE IF EXISTS processed_data");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_idempotency_records");
        jdbcTemplate.execute("""
                CREATE TABLE processed_data (
                    processed_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data VARCHAR(8192) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_idempotency_records (
                    idempotency_key_hash CHAR(64) PRIMARY KEY,
                    request_digest CHAR(64) NOT NULL,
                    response_body CLOB NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void writesTargetAndLedgerThenReplaysWithoutASecondTargetWrite() {
        EtlJobLease lease = lease(PAYLOAD, sha256(PAYLOAD));

        String firstResponse = idempotencyService.process(lease);
        String replayedResponse = idempotencyService.process(lease);

        assertEquals("Processed: record_alpha", firstResponse);
        assertEquals(firstResponse, replayedResponse);
        assertEquals(1, count("processed_data"));
        assertEquals(1, count("etl_idempotency_records"));
        verify(requestLock, org.mockito.Mockito.times(2)).tryLock(anyString());
    }

    @Test
    void rejectsPayloadDigestMismatchBeforeLockOrWrites() {
        EtlJobLease lease = lease(PAYLOAD, "c".repeat(64));

        EtlJobIntegrityException exception = assertThrows(
                EtlJobIntegrityException.class,
                () -> idempotencyService.process(lease)
        );

        assertEquals("etl_job_integrity_failure", exception.failureCode());
        verify(requestLock, never()).tryLock(anyString());
        assertEquals(0, count("processed_data"));
        assertEquals(0, count("etl_idempotency_records"));
    }

    @Test
    void rejectsConflictingStoredDigestWithoutAnotherTargetWrite() {
        EtlJobLease lease = lease(PAYLOAD, sha256(PAYLOAD));
        idempotencyService.process(lease);
        jdbcTemplate.update(
                "UPDATE etl_idempotency_records SET request_digest = ?",
                "d".repeat(64)
        );

        assertThrows(EtlJobIntegrityException.class, () -> idempotencyService.process(lease));

        assertEquals(1, count("processed_data"));
        assertEquals(1, count("etl_idempotency_records"));
    }

    @Test
    void reportsBusyLedgerAsTransientWithoutWrites() {
        when(requestLock.tryLock(anyString())).thenReturn(false);
        EtlJobLease lease = lease(PAYLOAD, sha256(PAYLOAD));

        assertThrows(CannotAcquireLockException.class, () -> idempotencyService.process(lease));

        assertEquals(0, count("processed_data"));
        assertEquals(0, count("etl_idempotency_records"));
    }

    @Test
    void failsClosedWithoutARealTransaction() {
        EtlJobIdempotencyService directService = new EtlJobIdempotencyService(
                jdbcTemplate,
                etlService,
                requestLock
        );

        assertThrows(IllegalStateException.class, () -> directService.process(
                lease(PAYLOAD, sha256(PAYLOAD))
        ));
        verify(requestLock, never()).tryLock(anyString());
    }

    @Test
    void rejectsMissingCollaboratorsAndLease() {
        assertThrows(
                NullPointerException.class,
                () -> new EtlJobIdempotencyService(null, etlService, requestLock)
        );
        assertThrows(
                NullPointerException.class,
                () -> new EtlJobIdempotencyService(jdbcTemplate, null, requestLock)
        );
        assertThrows(
                NullPointerException.class,
                () -> new EtlJobIdempotencyService(jdbcTemplate, etlService, null)
        );
        assertThrows(NullPointerException.class, () -> idempotencyService.process(null));
    }

    private int count(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + tableName,
                Integer.class
        );
        return count == null ? 0 : count;
    }

    private static EtlJobLease lease(String payload, String requestDigest) {
        return new EtlJobLease(
                UUID.randomUUID(),
                UUID.randomUUID(),
                OWNER_ID,
                PRINCIPAL_SCOPE_HASH,
                SUBMISSION_KEY_HASH,
                requestDigest,
                payload,
                1,
                Instant.now().plusSeconds(300)
        );
    }

    private static String sha256(String value) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(value.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException exception) {
            throw new AssertionError(exception);
        }
    }

    /** Transaction-enabled service context backed by an isolated H2 database. */
    @Configuration
    @EnableTransactionManagement
    static class TestConfiguration {

        @Bean
        DataSource dataSource() {
            return new EmbeddedDatabaseBuilder()
                    .generateUniqueName(true)
                    .setType(EmbeddedDatabaseType.H2)
                    .build();
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        EtlBatchProperties etlBatchProperties() {
            return new EtlBatchProperties();
        }

        @Bean
        ObjectMapper objectMapper() {
            return new ObjectMapper();
        }

        @Bean
        EtlRequestLock etlRequestLock() {
            return mock(EtlRequestLock.class);
        }

        @Bean
        EtlService etlService(
                JdbcTemplate jdbcTemplate,
                ObjectMapper objectMapper,
                EtlBatchProperties properties,
                EtlRequestLock requestLock
        ) {
            return new EtlService(jdbcTemplate, objectMapper, properties, requestLock);
        }

        @Bean
        EtlJobIdempotencyService etlJobIdempotencyService(
                JdbcTemplate jdbcTemplate,
                EtlService etlService,
                EtlRequestLock requestLock
        ) {
            return new EtlJobIdempotencyService(jdbcTemplate, etlService, requestLock);
        }
    }
}
