package com.xtrmetl.etl.job;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Proves that cancellation committed before exact-lease success rolls back target and ledger work.
 */
@SpringJUnitConfig(EtlJobCancellationAtomicityIntegrationTest.TestConfiguration.class)
class EtlJobCancellationAtomicityIntegrationTest {

    private static final String OWNER_ID = "worker-alpha";
    private static final String PAYLOAD = "[{\"id\":\"record_alpha\"}]";
    private static final String PRINCIPAL_SCOPE_HASH = "a".repeat(64);
    private static final String SUBMISSION_KEY_HASH = "b".repeat(64);
    private static final String REQUEST_DIGEST = "c".repeat(64);

    private final EtlJobLeaseRepository leaseRepository;
    private final JdbcTemplate jdbcTemplate;
    private final PlatformTransactionManager transactionManager;

    @Autowired
    EtlJobCancellationAtomicityIntegrationTest(
            EtlJobLeaseRepository leaseRepository,
            JdbcTemplate jdbcTemplate,
            PlatformTransactionManager transactionManager
    ) {
        this.leaseRepository = leaseRepository;
        this.jdbcTemplate = jdbcTemplate;
        this.transactionManager = transactionManager;
    }

    @BeforeEach
    void createTables() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS processed_data");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_idempotency_records");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_job_records");
        jdbcTemplate.execute("""
                CREATE TABLE etl_job_records (
                    job_record_id UUID PRIMARY KEY,
                    principal_scope_hash CHAR(64) NOT NULL,
                    submission_key_hash CHAR(64) NOT NULL,
                    request_digest CHAR(64) NOT NULL,
                    request_payload CLOB,
                    job_status VARCHAR(32) NOT NULL,
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    failure_code VARCHAR(128),
                    lease_claim_id UUID,
                    lease_owner_id VARCHAR(128),
                    lease_expires_at TIMESTAMP WITH TIME ZONE,
                    cancellation_key_hash CHAR(64),
                    cancellation_code VARCHAR(128),
                    job_cancelled_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE processed_data (
                    processed_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data VARCHAR(8192) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_idempotency_records (
                    idempotency_key_hash CHAR(64) PRIMARY KEY,
                    request_digest CHAR(64) NOT NULL,
                    response_body CLOB NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void cancellationCommitMakesSuccessStaleAndRollsBackEarlierEffects() {
        UUID jobRecordId = insertPendingJob();
        EtlJobLease lease = leaseRepository.claimNext(
                OWNER_ID,
                Duration.ofMinutes(5),
                3
        ).orElseThrow();

        EtlJobIdempotencyService idempotencyService = mock(EtlJobIdempotencyService.class);
        when(idempotencyService.process(lease)).thenAnswer(invocation -> {
            jdbcTemplate.update(
                    "INSERT INTO processed_data (data) VALUES (?)",
                    "ID:record_alpha,"
            );
            jdbcTemplate.update(
                    """
                    INSERT INTO etl_idempotency_records (
                        idempotency_key_hash, request_digest, response_body
                    ) VALUES (?, ?, ?)
                    """,
                    "d".repeat(64),
                    REQUEST_DIGEST,
                    "ID:record_alpha,"
            );
            cancelInIndependentTransaction(jobRecordId);
            return "ID:record_alpha,";
        });
        EtlJobExecutionService executionService = new EtlJobExecutionService(
                idempotencyService,
                leaseRepository
        );
        TransactionTemplate executionTransaction = new TransactionTemplate(transactionManager);

        assertThrows(
                StaleEtlJobLeaseException.class,
                () -> executionTransaction.executeWithoutResult(
                        status -> executionService.execute(lease)
                )
        );

        assertEquals(0, tableCount("processed_data"));
        assertEquals(0, tableCount("etl_idempotency_records"));
        assertEquals("CANCELLED", textColumn(jobRecordId, "job_status"));
        assertNull(textColumn(jobRecordId, "request_payload"));
        assertEquals(
                EtlJobService.CANCELLED_BY_OWNER_CODE,
                textColumn(jobRecordId, "cancellation_code")
        );
    }

    private void cancelInIndependentTransaction(UUID jobRecordId) {
        TransactionTemplate cancellationTransaction = new TransactionTemplate(transactionManager);
        cancellationTransaction.setPropagationBehavior(
                TransactionDefinition.PROPAGATION_REQUIRES_NEW
        );
        cancellationTransaction.executeWithoutResult(status -> {
            int cancelledRows = jdbcTemplate.update(
                    """
                    UPDATE etl_job_records
                    SET job_status = 'CANCELLED',
                        request_payload = NULL,
                        failure_code = NULL,
                        lease_claim_id = NULL,
                        lease_owner_id = NULL,
                        lease_expires_at = NULL,
                        cancellation_key_hash = ?,
                        cancellation_code = ?,
                        job_cancelled_at = CURRENT_TIMESTAMP,
                        updated_at = CURRENT_TIMESTAMP
                    WHERE job_record_id = ?
                      AND principal_scope_hash = ?
                      AND job_status IN ('PENDING', 'RUNNING')
                    """,
                    "e".repeat(64),
                    EtlJobService.CANCELLED_BY_OWNER_CODE,
                    jobRecordId,
                    PRINCIPAL_SCOPE_HASH
            );
            if (cancelledRows != 1) {
                throw new AssertionError("test cancellation did not update exactly one row");
            }
        });
    }

    private UUID insertPendingJob() {
        UUID jobRecordId = UUID.fromString("da381d2a-a4a5-41ad-a12a-9ac9b857193f");
        Instant now = Instant.parse("2026-08-06T00:00:00Z");
        jdbcTemplate.update(
                """
                INSERT INTO etl_job_records (
                    job_record_id, principal_scope_hash, submission_key_hash,
                    request_digest, request_payload, job_status, attempt_count,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, 'PENDING', 0, ?, ?)
                """,
                jobRecordId,
                PRINCIPAL_SCOPE_HASH,
                SUBMISSION_KEY_HASH,
                REQUEST_DIGEST,
                PAYLOAD,
                now,
                now
        );
        return jobRecordId;
    }

    private int tableCount(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + tableName,
                Integer.class
        );
        return count == null ? 0 : count;
    }

    private String textColumn(UUID jobRecordId, String columnName) {
        return jdbcTemplate.queryForObject(
                "SELECT " + columnName + " FROM etl_job_records WHERE job_record_id = ?",
                String.class,
                jobRecordId
        );
    }

    /** Minimal transaction-enabled context for cancellation-versus-success atomicity. */
    @Configuration
    @EnableTransactionManagement
    static class TestConfiguration {

        @Bean
        DataSource dataSource() {
            return new EmbeddedDatabaseBuilder()
                    .generateUniqueName(true)
                    .setType(EmbeddedDatabaseType.H2)
                    .build();
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        EtlJobLeaseRepository etlJobLeaseRepository(
                JdbcTemplate jdbcTemplate,
                PlatformTransactionManager transactionManager
        ) {
            return new EtlJobLeaseRepository(jdbcTemplate, transactionManager);
        }
    }
}
