package com.xtrmetl.etl.job;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.UUID;

/**
 * Shared in-memory transactional schema for durable-worker integration tests.
 */
final class EtlJobTestDatabase {

    private EtlJobTestDatabase() {
    }

    static DataSource newDataSource() {
        return new EmbeddedDatabaseBuilder()
                .generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2)
                .build();
    }

    static void createSchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_job_records");
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_idempotency_records");
        jdbcTemplate.execute("DROP TABLE IF EXISTS processed_data");
        jdbcTemplate.execute("""
                CREATE TABLE processed_data (
                    processed_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data VARCHAR(8192) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_idempotency_records (
                    idempotency_key_hash VARCHAR(64) PRIMARY KEY,
                    request_digest VARCHAR(64) NOT NULL,
                    response_body VARCHAR(8192) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_job_records (
                    job_record_id UUID PRIMARY KEY,
                    principal_scope_hash VARCHAR(64) NOT NULL,
                    submission_key_hash VARCHAR(64) NOT NULL,
                    request_digest VARCHAR(64) NOT NULL,
                    request_payload VARCHAR(8192),
                    job_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                    attempt_count INTEGER NOT NULL DEFAULT 0,
                    failure_code VARCHAR(128),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    lease_token UUID,
                    lease_expires_at TIMESTAMP WITH TIME ZONE,
                    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    processed_record_count INTEGER,
                    CONSTRAINT etl_job_submission_scope_unique
                        UNIQUE (principal_scope_hash, submission_key_hash),
                    CONSTRAINT etl_job_status_value_check CHECK (
                        job_status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')
                    ),
                    CONSTRAINT etl_job_payload_lifecycle_check CHECK (
                        (job_status IN ('PENDING', 'RUNNING') AND request_payload IS NOT NULL)
                        OR (job_status IN ('SUCCEEDED', 'FAILED') AND request_payload IS NULL)
                    ),
                    CONSTRAINT etl_job_attempt_count_nonnegative CHECK (attempt_count >= 0),
                    CONSTRAINT etl_job_running_lease_state_check CHECK (
                        (job_status = 'RUNNING'
                            AND lease_token IS NOT NULL
                            AND lease_expires_at IS NOT NULL)
                        OR (job_status <> 'RUNNING'
                            AND lease_token IS NULL
                            AND lease_expires_at IS NULL)
                    ),
                    CONSTRAINT etl_job_processed_record_count_check CHECK (
                        (job_status = 'SUCCEEDED' AND processed_record_count IS NOT NULL
                            AND processed_record_count >= 0)
                        OR (job_status <> 'SUCCEEDED' AND processed_record_count IS NULL)
                    ),
                    CONSTRAINT etl_job_failure_state_check CHECK (
                        (job_status = 'FAILED' AND failure_code IS NOT NULL)
                        OR (job_status <> 'FAILED' AND failure_code IS NULL)
                    )
                )
                """);
    }

    static UUID insertPending(
            JdbcTemplate jdbcTemplate,
            UUID jobRecordId,
            String payload,
            int attemptCount,
            Instant nextAttemptAt,
            Instant createdAt
    ) {
        jdbcTemplate.update(
                """
                INSERT INTO etl_job_records (
                    job_record_id,
                    principal_scope_hash,
                    submission_key_hash,
                    request_digest,
                    request_payload,
                    job_status,
                    attempt_count,
                    created_at,
                    updated_at,
                    next_attempt_at
                ) VALUES (?, ?, ?, ?, ?, 'PENDING', ?, ?, ?, ?)
                """,
                jobRecordId,
                repeatedHex('a', jobRecordId),
                repeatedHex('b', jobRecordId),
                repeatedHex('c', jobRecordId),
                payload,
                attemptCount,
                Timestamp.from(createdAt),
                Timestamp.from(createdAt),
                Timestamp.from(nextAttemptAt)
        );
        return jobRecordId;
    }

    static void insertRunning(
            JdbcTemplate jdbcTemplate,
            UUID jobRecordId,
            UUID leaseToken,
            String payload,
            int attemptCount,
            Instant leaseExpiresAt,
            Instant createdAt
    ) {
        jdbcTemplate.update(
                """
                INSERT INTO etl_job_records (
                    job_record_id,
                    principal_scope_hash,
                    submission_key_hash,
                    request_digest,
                    request_payload,
                    job_status,
                    attempt_count,
                    created_at,
                    updated_at,
                    lease_token,
                    lease_expires_at,
                    next_attempt_at
                ) VALUES (?, ?, ?, ?, ?, 'RUNNING', ?, ?, ?, ?, ?, ?)
                """,
                jobRecordId,
                repeatedHex('d', jobRecordId),
                repeatedHex('e', jobRecordId),
                repeatedHex('f', jobRecordId),
                payload,
                attemptCount,
                Timestamp.from(createdAt),
                Timestamp.from(createdAt),
                leaseToken,
                Timestamp.from(leaseExpiresAt),
                Timestamp.from(createdAt)
        );
    }

    private static String repeatedHex(char character, UUID jobRecordId) {
        String suffix = jobRecordId.toString().replace("-", "");
        return String.valueOf(character).repeat(32) + suffix;
    }
}
