server:
  port: 8001

spring:
  application:
    name: cdc-service
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  zipkin:
    baseUrl: http://localhost:9412
  sleuth:
    sampler:
      probability: 1.0

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.xtrmetl: DEBUG
    io.debezium: INFO
    org.springframework.web: DEBUG
