package com.xtrmetl.etl.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Proves worker execution can compose the durable ETL ledger inside its caller transaction.
 */
@SpringJUnitConfig(EtlServiceTransactionScopedIdempotencyIntegrationTest.TestConfiguration.class)
class EtlServiceTransactionScopedIdempotencyIntegrationTest {

    private static final String PAYLOAD = "[{\"id\":\"record_alpha\",\"name\":\"Ada\"}]";
    private static final String KEY = "cf4f083f-8c90-4f34-a8b6-b53761de44ef";
    private static final String SCOPE = "durable_etl_job_worker";

    private final EtlService etlService;
    private final JdbcTemplate jdbcTemplate;
    private final PlatformTransactionManager transactionManager;

    @Autowired
    EtlServiceTransactionScopedIdempotencyIntegrationTest(
            EtlService etlService,
            JdbcTemplate jdbcTemplate,
            PlatformTransactionManager transactionManager
    ) {
        this.etlService = etlService;
        this.jdbcTemplate = jdbcTemplate;
        this.transactionManager = transactionManager;
    }

    @BeforeEach
    void resetSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS etl_idempotency_records");
        jdbcTemplate.execute("DROP TABLE IF EXISTS processed_data");
        jdbcTemplate.execute("""
                CREATE TABLE processed_data (
                    processed_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    data VARCHAR(8192) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE etl_idempotency_records (
                    idempotency_key_hash VARCHAR(64) PRIMARY KEY,
                    request_digest VARCHAR(64) NOT NULL,
                    response_body VARCHAR(8192) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void refusesTheSingleAttemptPortWithoutACallerTransaction() {
        IllegalStateException exception = assertThrows(
                IllegalStateException.class,
                () -> etlService.processDataIdempotentlyInCurrentTransaction(PAYLOAD, KEY, SCOPE)
        );

        assertEquals(
                "Idempotent ETL processing requires an active transaction",
                exception.getMessage()
        );
        assertEquals(0, count("processed_data"));
        assertEquals(0, count("etl_idempotency_records"));
    }

    @Test
    void commitsAndReplaysInsideCallerOwnedTransactions() {
        TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);

        EtlIdempotencyResult first = transactionTemplate.execute(
                status -> etlService.processDataIdempotentlyInCurrentTransaction(
                        PAYLOAD,
                        KEY,
                        SCOPE
                )
        );
        EtlIdempotencyResult replay = transactionTemplate.execute(
                status -> etlService.processDataIdempotentlyInCurrentTransaction(
                        PAYLOAD,
                        KEY,
                        SCOPE
                )
        );

        assertFalse(first.replayed());
        assertTrue(replay.replayed());
        assertEquals(first.responseBody(), replay.responseBody());
        assertEquals(1, count("processed_data"));
        assertEquals(1, count("etl_idempotency_records"));
    }

    @Test
    void rollsBackTargetAndLedgerWithTheCallerTransaction() {
        TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);

        transactionTemplate.executeWithoutResult(status -> {
            EtlIdempotencyResult result = etlService.processDataIdempotentlyInCurrentTransaction(
                    PAYLOAD,
                    KEY,
                    SCOPE
            );
            assertFalse(result.replayed());
            status.setRollbackOnly();
        });

        assertEquals(0, count("processed_data"));
        assertEquals(0, count("etl_idempotency_records"));
    }

    private int count(String tableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM " + tableName,
                Integer.class
        );
        return count == null ? 0 : count;
    }

    /**
     * Minimal real-transaction service context.
     */
    @Configuration
    @EnableTransactionManagement
    static class TestConfiguration {

        @Bean
        DataSource dataSource() {
            return new EmbeddedDatabaseBuilder()
                    .generateUniqueName(true)
                    .setType(EmbeddedDatabaseType.H2)
                    .build();
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        ObjectMapper objectMapper() {
            return new ObjectMapper();
        }

        @Bean
        EtlBatchProperties etlBatchProperties() {
            return new EtlBatchProperties();
        }

        @Bean
        EtlRequestLock etlRequestLock() {
            return idempotencyKeyHash -> true;
        }

        @Bean
        EtlService etlService(
                JdbcTemplate jdbcTemplate,
                ObjectMapper objectMapper,
                EtlBatchProperties properties,
                EtlRequestLock requestLock
        ) {
            return new EtlService(jdbcTemplate, objectMapper, properties, requestLock);
        }
    }
}
