server:
  port: 8080

spring:
  application:
    name: zuul-gateway
  cloud:
    gateway:
      routes:
        - id: etl-service
          uri: lb://etl-service
          predicates:
            - Path=/etl/**
          filters:
            - StripPrefix=1
        - id: cdc-service
          uri: lb://cdc-service
          predicates:
            - Path=/cdc/**
          filters:
            - StripPrefix=1

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9412/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

logging:
  level:
    root: INFO
    com:
      xtrmetl: DEBUG
    org:
      springframework:
        web: DEBUG
